name: Deploy development backend

on:
  push:
    branches:
      - development

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: "development"
