name: Deploy backend to Google Cloud Run

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     version: "latest"
      #     project_id: ${{ env.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Configure Docker"
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          cd backend && docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/backend:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/backend:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/backend:$GITHUB_SHA \
            --platform managed \
            --allow-unauthenticated \
            --region "${{ vars.GCP_REGION }}"
