name: Deploy production backend

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      environment: "production"
