name: Deploy backend to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy-backend-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     version: "latest"
      #     project_id: ${{ env.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Build Docker image
        env:
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
        run: |
          cd backend && docker build -t gcr.io/$GCP_PROJECT_ID/backend:$GITHUB_SHA .

      - name: Push Docker image
        env:
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
        run: |
          docker push gcr.io/$env.GCP_PROJECT_ID/backend:$GITHUB_SHA

      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
        run: |
          gcloud run deploy backend \
            --image gcr.io/$env.GCP_PROJECT_ID/backend:$GITHUB_SHA \
            --platform managed \
            --allow-unauthenticated
